authentication:
    api_key: 'API_KEY'
    api_secret_key: 'API_SECRET_KEY'
    api_url: 'https://cloudstack/client/api'

# zone type basic or advanced
cloudstack:
    zone_type: 'basic'    

    
compute:
    management_server:
        user_on_management: root
        userhome_on_management: /root
        instance:
            use_existing: false
            name: cloudify-management-server
            image: 299fd26a-2b4f-4ff4-acfd-23d2682d65ba
            size: Medium
        management_keypair:
            use_existing: true
            name: cloudify-management-kp
#            provided:
#                public_key_filepath:
#                private_key_filepath: ~/.ssh/cloudify-management-kp.pem
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-management-kp.pem
    agent_servers:
        agents_keypair:
            use_existing: true
            name: cloudify-agents-kp
#            provided:
#                public_key_filepath:
#                private_key_filepath: ~/.ssh/cloudify-agents-kp.pem
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-agents-kp.pem


networking:
    agents_network:
        use_existing: true
        name: cloudify-agents-network
        public_ip: xxx.xxx.xxx.xxx
        protocol: TCP
        cidr: 0.0.0.0/0
        ports: [22, 27017, 28017, 8080]
    management_network:
        use_existing: true
        name: cloudify-management-network
        public_ip: xxx.xxx.xxx.xxx
        protocol: TCP
        cidr: 0.0.0.0/0
        ports: [5555, 5672, 53229, 22, 8100, 80]

cloudify:
    cloudify_components_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-components_amd64.deb
    cloudify_core_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-core_amd64.deb
    cloudify_ui_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-ui_amd64.deb
    cloudify_ubuntu_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/ubuntu-agent_amd64.deb

    cloudify_agent:
        min_workers: 2
        max_workers: 5
        remote_execution_port: 22
        #user: (no default - optional parameter)
